-- Phase 4 — passive feedback signal for podcast episodes.
--
-- read_state.passive_feedback: derived from listened-percent at the
-- player layer. ≥80% played ⇒ +1 (positive), <10% played after >30s
-- of playback ⇒ -1 (skip). Sits alongside the explicit
-- read_state.feedback column from Phase 3, with explicit always
-- winning at write time (the route checks before persisting).
--
-- Why a separate column instead of overwriting `feedback`:
-- explicit valence is a stronger signal than passive listening, and
-- the ranker (Phase 6) will probably want to weight them differently
-- (e.g. explicit ±1, passive ±0.5). Keeping them separate also means
-- a 👍 the user gave on /article/:uid never gets clobbered by a
-- premature pagehide.
--
-- Default 0 = no passive signal yet. Read paths are unchanged until
-- the Phase 6 ranker consumes the column.
ALTER TABLE read_state ADD COLUMN passive_feedback INTEGER NOT NULL DEFAULT 0;
